<?php

namespace AppBundle\Repository;

/**
 * CuadradoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuadradoRepository extends \Doctrine\ORM\EntityRepository
{
}
