<?php

namespace AppBundle\Repository;

/**
 * HexagonoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HexagonoRepository extends \Doctrine\ORM\EntityRepository
{
}
