<?php

namespace AppBundle\Repository;

/**
 * TrianguloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrianguloRepository extends \Doctrine\ORM\EntityRepository
{
}
